package pe.edu.upeu.navegationjpc.ui.theme

import androidx.compose.ui.graphics.Color

val textColor=Color(0xFF6650a4)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val green_primaryLight = Color(0xFF8F4A4B)
val green_onPrimaryLight = Color(0xFFFFFFFF)
val green_primaryContainerLight = Color(0xFFFFDAD9)
val green_onPrimaryContainerLight = Color(0xFF733335)
val green_secondaryLight = Color(0xFF775656)
val green_onSecondaryLight = Color(0xFFFFFFFF)
val green_secondaryContainerLight = Color(0xFFFFDAD9)
val green_onSecondaryContainerLight = Color(0xFF5D3F3F)
val green_tertiaryLight = Color(0xFF7D570E)
val green_onTertiaryLight = Color(0xFFFFFFFF)
val green_tertiaryContainerLight = Color(0xFFFFDEAD)
val green_onTertiaryContainerLight = Color(0xFF604100)
val green_errorLight = Color(0xFFBA1A1A)
val green_onErrorLight = Color(0xFFFFFFFF)
val green_errorContainerLight = Color(0xFFFFDAD6)
val green_onErrorContainerLight = Color(0xFF93000A)
val green_backgroundLight = Color(0xFFFFF8F7)
val green_onBackgroundLight = Color(0xFF221919)
val green_surfaceLight = Color(0xFFFFF8F7)
val green_onSurfaceLight = Color(0xFF221919)
val green_surfaceVariantLight = Color(0xFFF2DDE1)
val green_onSurfaceVariantLight = Color(0xFF514347)
val green_outlineLight = Color(0xFF837377)
val green_outlineVariantLight = Color(0xFFD5C2C6)
val green_scrimLight = Color(0xFF000000)
val green_inverseSurfaceLight = Color(0xFF382E2E)
val green_inverseOnSurfaceLight = Color(0xFFFFEDEC)
val green_inversePrimaryLight = Color(0xFFFFB3B3)
val green_surfaceDimLight = Color(0xFFE8D6D5)
val green_surfaceBrightLight = Color(0xFFFFF8F7)
val green_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val green_surfaceContainerLowLight = Color(0xFFFFF0EF)
val green_surfaceContainerLight = Color(0xFFFCEAE9)
val green_surfaceContainerHighLight = Color(0xFFF6E4E3)
val green_surfaceContainerHighestLight = Color(0xFFF0DEDE)

//DARK COLOR
val green_primaryDark = Color(0xFFFFB3B3)
val green_onPrimaryDark = Color(0xFF561D20)
val green_primaryContainerDark = Color(0xFF733335)
val green_onPrimaryContainerDark = Color(0xFFFFDAD9)
val green_secondaryDark = Color(0xFFE6BDBC)
val green_onSecondaryDark = Color(0xFF442929)
val green_secondaryContainerDark = Color(0xFF5D3F3F)
val green_onSecondaryContainerDark = Color(0xFFFFDAD9)
val green_tertiaryDark = Color(0xFFF1BE6D)
val green_onTertiaryDark = Color(0xFF432C00)
val green_tertiaryContainerDark = Color(0xFF604100)
val green_onTertiaryContainerDark = Color(0xFFFFDEAD)
val green_errorDark = Color(0xFFFFB4AB)
val green_onErrorDark = Color(0xFF690005)
val green_errorContainerDark = Color(0xFF93000A)
val green_onErrorContainerDark = Color(0xFFFFDAD6)
val green_backgroundDark = Color(0xFF1A1111)
val green_onBackgroundDark = Color(0xFFF0DEDE)
val green_surfaceDark = Color(0xFF1A1111)
val green_onSurfaceDark = Color(0xFFF0DEDE)
val green_surfaceVariantDark = Color(0xFF514347)
val green_onSurfaceVariantDark = Color(0xFFD5C2C6)
val green_outlineDark = Color(0xFF9E8C90)
val green_outlineVariantDark = Color(0xFF514347)
val green_scrimDark = Color(0xFF000000)
val green_inverseSurfaceDark = Color(0xFFF0DEDE)
val green_inverseOnSurfaceDark = Color(0xFF382E2E)
val green_inversePrimaryDark = Color(0xFF8F4A4B)
val green_surfaceDimDark = Color(0xFF1A1111)
val green_surfaceBrightDark = Color(0xFF423736)
val green_surfaceContainerLowestDark = Color(0xFF140C0C)
val green_surfaceContainerLowDark = Color(0xFF221919)
val green_surfaceContainerDark = Color(0xFF271D1D)
val green_surfaceContainerHighDark = Color(0xFF322827)
val green_surfaceContainerHighestDark = Color(0xFF3D3232)




//RED

val red_primaryLight = Color(0xFF4C662B)
val red_onPrimaryLight = Color(0xFFFFFFFF)
val red_primaryContainerLight = Color(0xFFCDEDA3)
val red_onPrimaryContainerLight = Color(0xFF354E16)
val red_secondaryLight = Color(0xFF586249)
val red_onSecondaryLight = Color(0xFFFFFFFF)
val red_secondaryContainerLight = Color(0xFFDCE7C8)
val red_onSecondaryContainerLight = Color(0xFF404A33)
val red_tertiaryLight = Color(0xFF386663)
val red_onTertiaryLight = Color(0xFFFFFFFF)
val red_tertiaryContainerLight = Color(0xFFBCECE7)
val red_onTertiaryContainerLight = Color(0xFF1F4E4B)
val red_errorLight = Color(0xFFBA1A1A)
val red_onErrorLight = Color(0xFFFFFFFF)
val red_errorContainerLight = Color(0xFFFFDAD6)
val red_onErrorContainerLight = Color(0xFF93000A)
val red_backgroundLight = Color(0xFFF9FAEF)
val red_onBackgroundLight = Color(0xFF1A1C16)
val red_surfaceLight = Color(0xFFF9FAEF)
val red_onSurfaceLight = Color(0xFF1A1C16)
val red_surfaceVariantLight = Color(0xFFE1E4D5)
val red_onSurfaceVariantLight = Color(0xFF44483D)
val red_outlineLight = Color(0xFF75796C)
val red_outlineVariantLight = Color(0xFFC5C8BA)
val red_scrimLight = Color(0xFF000000)
val red_inverseSurfaceLight = Color(0xFF2F312A)
val red_inverseOnSurfaceLight = Color(0xFFF1F2E6)
val red_inversePrimaryLight = Color(0xFFB1D18A)
val red_surfaceDimLight = Color(0xFFDADBD0)
val red_surfaceBrightLight = Color(0xFFF9FAEF)
val red_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val red_surfaceContainerLowLight = Color(0xFFF3F4E9)
val red_surfaceContainerLight = Color(0xFFEEEFE3)
val red_surfaceContainerHighLight = Color(0xFFE8E9DE)
val red_surfaceContainerHighestLight = Color(0xFFE2E3D8)

//RED DARK

val red_primaryDark = Color(0xFFB1D18A)
val red_onPrimaryDark = Color(0xFF1F3701)
val red_primaryContainerDark = Color(0xFF354E16)
val red_onPrimaryContainerDark = Color(0xFFCDEDA3)
val red_secondaryDark = Color(0xFFBFCBAD)
val red_onSecondaryDark = Color(0xFF2A331E)
val red_secondaryContainerDark = Color(0xFF404A33)
val red_onSecondaryContainerDark = Color(0xFFDCE7C8)
val red_tertiaryDark = Color(0xFFA0D0CB)
val red_onTertiaryDark = Color(0xFF003735)
val red_tertiaryContainerDark = Color(0xFF1F4E4B)
val red_onTertiaryContainerDark = Color(0xFFBCECE7)
val red_errorDark = Color(0xFFFFB4AB)
val red_onErrorDark = Color(0xFF690005)
val red_errorContainerDark = Color(0xFF93000A)
val red_onErrorContainerDark = Color(0xFFFFDAD6)
val red_backgroundDark = Color(0xFF12140E)
val red_onBackgroundDark = Color(0xFFE2E3D8)
val red_surfaceDark = Color(0xFF12140E)
val red_onSurfaceDark = Color(0xFFE2E3D8)
val red_surfaceVariantDark = Color(0xFF44483D)
val red_onSurfaceVariantDark = Color(0xFFC5C8BA)
val red_outlineDark = Color(0xFF8F9285)
val red_outlineVariantDark = Color(0xFF44483D)
val red_scrimDark = Color(0xFF000000)
val red_inverseSurfaceDark = Color(0xFFE2E3D8)
val red_inverseOnSurfaceDark = Color(0xFF2F312A)
val red_inversePrimaryDark = Color(0xFF4C662B)
val red_surfaceDimDark = Color(0xFF12140E)
val red_surfaceBrightDark = Color(0xFF383A32)
val red_surfaceContainerLowestDark = Color(0xFF0C0F09)
val red_surfaceContainerLowDark = Color(0xFF1A1C16)
val red_surfaceContainerDark = Color(0xFF1E201A)
val red_surfaceContainerHighDark = Color(0xFF282B24)
val red_surfaceContainerHighestDark = Color(0xFF33362E)
